# Production override file that implements Podman secrets
# Usage: podman-compose -f podman-compose.yml -f podman-compose.prod.yml up -d

version: '3.8'

services:
  postgres:
    # Remove password from environment, use secret instead
    environment:
      POSTGRES_DB: ankiquizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  backend:
    # Remove connection string from environment, use secret instead
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=ankiquizdb
      - POSTGRES_USER=postgres
      - POSTGRES_CONNECTION_STRING_FILE=/run/secrets/postgres_connection_string
      # POSTGRES_PASSWORD and POSTGRES_CONNECTION_STRING removed - using secrets
    secrets:
      - postgres_connection_string

secrets:
  postgres_password:
    external: true
  postgres_connection_string:
    external: true
