version: '3.8'

services:
  # Frontend only (backend now in LifeOS API / ArangoDB)
  frontend:
    build:
      context: ./Assessment
      dockerfile: Dockerfile
      target: production
    container_name: ankiquiz-frontend
    restart: unless-stopped
    environment:
      - DENO_ENV=production
      - VITE_API_URL=http://api:5120
      - VITE_UPLOADS_URL=http://api:5120
    ports:
      - "8010:8000"
    networks:
      - lifeos-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  lifeos-network:
    external: true
