# syntax=docker/dockerfile:1.4
FROM denoland/deno:latest AS base

ARG GIT_REVISION
ENV DENO_DEPLOYMENT_ID=${GIT_REVISION}
ENV DENO_NODE_MODULES_DIR=auto

WORKDIR /app

COPY deno.json deno.lock ./
COPY vite.config.ts main.tsx utils.ts ./

# Install locally
RUN deno install --allow-scripts

COPY . .

# Build locally
RUN deno task build

FROM denoland/deno:latest AS runtime

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

ARG GIT_REVISION
ENV DENO_DEPLOYMENT_ID=${GIT_REVISION}
ENV DENO_NODE_MODULES_DIR=auto

WORKDIR /app

COPY --from=base /app/_fresh ./_fresh
COPY --from=base /app/deno.json ./
COPY --from=base /app/deno.lock ./
COPY --from=base /app/static ./static
COPY --from=base /app/main.tsx ./
COPY --from=base /app/node_modules ./node_modules

EXPOSE 8000

CMD ["deno", "serve", "-A", "_fresh/server.js"]